# Generated by Django 4.2 on 2024-09-27 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='liquor/')),
                ('content', models.TextField()),
                ('taste', models.CharField(max_length=100)),
                ('abv', models.FloatField()),
                ('price', models.PositiveIntegerField()),
                ('bookmark', models.ManyToManyField(related_name='liquor_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
