# Generated by Django 4.2 on 2024-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='taste',
            field=models.CharField(max_length=500),
        ),
    ]
