# Generated by Django 4.2 on 2024-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='abv',
            field=models.FloatField(null=True),
        ),
    ]
