# Generated by Django 4.2 on 2024-10-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='image',
            new_name='img',
        ),
    ]
