# Generated by Django 4.2 on 2024-09-27 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='bookmark',
            field=models.ManyToManyField(related_name='cocktail_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='taste',
            field=models.CharField(max_length=500),
        ),
    ]
